INSERT INTO `airport` (`id`, `code`, `name`, `city_id`) VALUES (1, 'LAX', 'Los Angeles International Airport', 3);
INSERT INTO `airport` (`id`, `code`, `name`, `city_id`) VALUES (2, 'JFK', 'John F. Kennedy International Airport', 5);
INSERT INTO `airport` (`id`, `code`, `name`, `city_id`) VALUES (3, 'ORD', 'O\'Hare International Airport', 2);
INSERT INTO `airport` (`id`, `code`, `name`, `city_id`) VALUES (4, 'ATL', 'Hartsfield-Jackson Atlanta International Airport', 4);
INSERT INTO `airport` (`id`, `code`, `name`, `city_id`) VALUES (5, 'DFW', 'Dallas/Fort Worth International Airport', 1);
INSERT INTO `airport` (`id`, `code`, `name`, `city_id`) VALUES (6, 'DEN', 'Denver International Airport', 6);
INSERT INTO `airport` (`id`, `code`, `name`, `city_id`) VALUES (7, 'SEA', 'Seattle-Tacoma International Airport', 7);
INSERT INTO `airport` (`id`, `code`, `name`, `city_id`) VALUES (8, 'SFO', 'San Francisco International Airport', 10);
INSERT INTO `airport` (`id`, `code`, `name`, `city_id`) VALUES (9, 'MIA', 'Miami International Airport', 8);
INSERT INTO `airport` (`id`, `code`, `name`, `city_id`) VALUES (10, 'PHX', 'Phoenix Sky Harbor International Airport', 2);
INSERT INTO `airport` (`id`, `code`, `name`, `city_id`) VALUES (11, 'LAS', 'McCarran International Airport', 9);
INSERT INTO `airport` (`id`, `code`, `name`, `city_id`) VALUES (12, 'IAH', 'George Bush Intercontinental Airport', 5);
INSERT INTO `airport` (`id`, `code`, `name`, `city_id`) VALUES (13, 'BOS', 'Logan International Airport', 4);
INSERT INTO `airport` (`id`, `code`, `name`, `city_id`) VALUES (14, 'MSP', 'Minneapolis-Saint Paul International Airport', 6);
INSERT INTO `airport` (`id`, `code`, `name`, `city_id`) VALUES (15, 'FLL', 'Fort Lauderdale-Hollywood International Airport', 3);
INSERT INTO `airport` (`id`, `code`, `name`, `city_id`) VALUES (16, 'TPA', 'Tampa International Airport', 1);
INSERT INTO `airport` (`id`, `code`, `name`, `city_id`) VALUES (17, 'CLT', 'Charlotte Douglas International Airport', 8);
INSERT INTO `airport` (`id`, `code`, `name`, `city_id`) VALUES (18, 'DTW', 'Detroit Metropolitan Airport', 9);
INSERT INTO `airport` (`id`, `code`, `name`, `city_id`) VALUES (19, 'HNL', 'Daniel K. Inouye International Airport', 10);
INSERT INTO `airport` (`id`, `code`, `name`, `city_id`) VALUES (20, 'SLC', 'Salt Lake City International Airport', 7);
INSERT INTO `airport` (`id`, `code`, `name`, `city_id`) VALUES (21, 'BWI', 'Baltimore/Washington International Thurgood Marshall Airport', 3);
INSERT INTO `airport` (`id`, `code`, `name`, `city_id`) VALUES (22, 'SMF', 'Sacramento International Airport', 1);
INSERT INTO `airport` (`id`, `code`, `name`, `city_id`) VALUES (23, 'RDU', 'Raleigh-Durham International Airport', 2);
INSERT INTO `airport` (`id`, `code`, `name`, `city_id`) VALUES (24, 'MCO', 'Orlando International Airport', 5);
INSERT INTO `airport` (`id`, `code`, `name`, `city_id`) VALUES (25, 'BNA', 'Nashville International Airport', 6);
